version: '3.1'

services:
  lb:
      image: "jwilder/nginx-proxy"
      ports:
        - "8080:80"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro

  web:
    depends_on:
      - lb
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - VIRTUAL_HOST=localhost